CREATE TABLE IF NOT EXISTS csv_staging (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  batch_id      UUID NOT NULL,
  row_index     INT  NOT NULL,
  identificacion VARCHAR(20),
  paciente       VARCHAR(200),
  formula        VARCHAR(100),
  fecha          DATE,
  producto       VARCHAR(400),
  codigo         VARCHAR(80),
  estado         VARCHAR(50),
  direccion      TEXT,
  telefono       VARCHAR(30),
  tipo_medica    VARCHAR(20),
  condicionado   BOOLEAN,
  sucursal       VARCHAR(100),
  modalidad      VARCHAR(50),
  contrato       VARCHAR(50),
  clasificacion  VARCHAR(10),
  cp             VARCHAR(80),
  cl             VARCHAR(20),
  pendiente      INT,
  entregado      INT,
  existencia     INT,
  fecha_1        DATE,
  observacion_1  TEXT,
  usuario_1      VARCHAR(100),
  fecha_2        DATE,
  observacion_2  TEXT,
  usuario_2      VARCHAR(100),
  fecha_3        DATE,
  observacion_3  TEXT,
  usuario_3      VARCHAR(100),
  created_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_csv_staging_batch ON csv_staging(batch_id);
